title: Your Name
description: Scientist, explorer of the unknown
theme: null
logo: /assets/headshot.jpg
url: https://<your-username>.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope: {path: ""}
    values: {layout: default}
